MyHospital.Web/Controllers/DeseaseController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MyHospital.BLL.DTO;
using MyHospital.BLL.Infrastructure;
using MyHospital.BLL.Interfaces;
using MyHospital.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MyHospital.Web.Controllers
{
    [Authorize]
    public class DeseaseController : Controller
    {
        private IUserService UserService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IUserService>();
            }
        }

        private IDeseaseService DeseaseService
        {
            get;
        }

        public DeseaseController(IDeseaseService DeseaseService)
        {
            this.DeseaseService = DeseaseService;
            PageSize = 7;
        }

        public int PageSize { get; private set; }

        [HttpGet]
        public ActionResult Deseases(int Page = 0, string Name = "")
        {
            ViewBag.Role = GetRole();
            IEnumerable<DeseaseDTO> deseases;
            if (string.IsNullOrWhiteSpace(Name))
                deseases = DeseaseService.GetAllDesease(User.Identity.GetUserId());
            else
                deseases = DeseaseService.GetAllDesease().Where(x => x.Name == Name);
            ViewBag.Page = Page;
            var count = deseases.Count();
            ViewBag.PageCount = count / PageSize;
            if (count % PageSize != 0)
                ViewBag.PageCount += 1;
            ViewBag.Name = Name;
            return View(deseases.Skip(Page * PageSize).Take(PageSize));
        }

        [HttpGet]
        [Authorize(Roles = "patient")]
        public ActionResult CreateDesease(string DoctorId)
        {
            ViewBag.DoctorId = DoctorId;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "patient")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateDesease(CreateDeseaseModel Model)
        {
            var patientId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                OperationDetails operationDetails = await DeseaseService.CreateAsync(patientId, Model.DoctorId, Model.Complaint);
                if (operationDetails.Succedeed)
                {
                    return PartialView("SuccessCreateDesease");
                }
                else
                    ModelState.AddModelError(operationDetails.Property, operationDetails.Message);
            }
            return View(Model);
        }
        
        [HttpGet]
        public ActionResult UpdateDesease(int Id, string Message)
        {
            ViewBag.Role = GetRole();
            var desease = DeseaseService.GetDeseaseById(Id);
            var deseaseModel = new UpdateDeseaseModel { Id = Id, DoctorId = desease.DoctorId, DoctorName = desease.DoctorName, Status = desease.Status, Name = desease.Name, Message = Message, Complaint = desease.Complaint };
            var doctorsList = new SelectList(UserService.GetAllUsers().Where(x => x.Role == "doctor").Select(x => new { Id = x.Id, Name = x.Name, Specialization = ((DoctorDTO)x).Specialization }), "Id", "Name");
            var statusesList = new SelectList(DeseaseService.GetAllStatuses());
            ViewBag.doctor = doctorsList;
            ViewBag.statuses = statusesList;
            if (desease.EndDate == null)
                ViewBag.IsClosed = false;
            else
                ViewBag.IsClosed = true;
            return View(deseaseModel);
        }

        [HttpPost]
        [Authorize(Roles = "doctor, admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangeName(string Name, int DeseaseId)
        {
            string message = "";
            if (string.IsNullOrWhiteSpace(Name))
            {
                message = "Имя не может быть пустым";
            }
            else
            {
                OperationDetails operationDetails = await DeseaseService.ChangeName(DeseaseId, Name);
                message = operationDetails.Message;
            }
            return RedirectToAction("UpdateDesease", new { id = DeseaseId, message = message });
        }

        [HttpPost]
        [Authorize(Roles = "doctor, admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangeDoctor(string DoctorId, int DeseaseId)
        {
            string message = "";
            OperationDetails operationDetails = await DeseaseService.ChangeDoctor(DeseaseId, DoctorId);
            message = operationDetails.Message;
            return RedirectToAction("UpdateDesease", new { id = DeseaseId, message = message });
        }

        [HttpPost]
        [Authorize(Roles = "doctor, admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangeStatus(string Status, int DeseaseId)
        {
            string message = "";
            OperationDetails operationDetails = await DeseaseService.ChangeStatus(DeseaseId, Status);
            message = operationDetails.Message;
            return RedirectToAction("UpdateDesease", new { id = DeseaseId, message = message });
        }

        [HttpPost]
        [Authorize(Roles = "doctor, admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CloseDesease(int DeseaseId)
        {
            string message = "";
            OperationDetails operationDetails = await DeseaseService.CloseDesease(DeseaseId);
            message = operationDetails.Message;
            return RedirectToAction("UpdateDesease", new { id = DeseaseId, message = message });
        }

        [HttpPost]
        [Authorize(Roles = "doctor, admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ReOpenDesease(int DeseaseId)
        {
            string message = "";
            OperationDetails operationDetails = await DeseaseService.ReOpenDesease(DeseaseId);
            message = operationDetails.Message;
            return RedirectToAction("UpdateDesease", new { id = DeseaseId, message = message });
        }

        [HttpPost]
        [Authorize(Roles = "doctor, admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteDesease(int DeseaseId)
        {
            string message = "";
            OperationDetails operationDetails = await DeseaseService.DeleteDesease(DeseaseId);
            if (!operationDetails.Succedeed)
            {
                message = operationDetails.Message;
                return RedirectToAction("UpdateDesease", new { id = DeseaseId, message = message });
            }
            return RedirectToAction("Deseases");
        }

        [HttpGet]
        public ActionResult DeseaseHistory(int Id, string Message)
        {
            ViewBag.Role = GetRole();
            var desease = DeseaseService.GetDeseaseById(Id);
            var history = DeseaseService.GetAllRecords(Id);
            ViewBag.Id = Id;
            if (desease.EndDate == null)
                ViewBag.IsClosed = false;
            else
                ViewBag.IsClosed = true;
            return View(history);
        }

        [HttpPost]
        [Authorize(Roles = "doctor, admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddRecord(int DeseaseId, string Text)
        {
            string message = "";
            OperationDetails operationDetails = await DeseaseService.AddRecord(DeseaseId, Text);
            message = operationDetails.Message;
            return RedirectToAction("DeseaseHistory", new { id = DeseaseId, message = message });
        }

        private string GetRole()
        {
            var userId = User.Identity.GetUserId();
            if (UserService.IsInRole(userId, "doctor"))
                return "doctor";
            else if (UserService.IsInRole(userId, "patient"))
                return "patient";
            else if (UserService.IsInRole(userId, "admin"))
                return "admin";
            else
                return "norole";
        }
    }
}

MyHospital.Web/Views/Desease/CreateDesease.cshtml
@model MyHospital.Web.Models.CreateDeseaseModel

<div>

    @using (Html.BeginForm("CreateDesease", "Desease", FormMethod.Post, new { @class = "form-horizontal", id = "createDeseaseForm" }))
    {
        @Html.AntiForgeryToken();

        @Html.ValidationSummary();
        <div class="form-group">
            <label for="name">Жалоба:</label>
            @Html.TextAreaFor(x => x.Complaint, new { @class = "form-control", placeholder = "Жалоба", id = "name" })
        </div>
        <div class="form-group">
            @Html.HiddenFor(x => x.DoctorId, new { id = "doctor", value = ViewBag.DoctorId })
        </div>
        <div class="form-group">
            <input class="btn btn-info" id="CreateDesease" type="submit" value="Создать" />
        </div>
    }
</div>

@section menu{
    <div id="Update" class="menu-item active">
        <p>Создать болезнь</p>
    </div>
    <div id="ReverseToDoctors" class="menu-item">
        <p>Вернуться</p>
    </div>
}

@section script{
    @Scripts.Render("~/bundles/myscripts")
}

MyHospital.Web/Views/Desease/DeseaseHistory.cshtml
@model IEnumerable<MyHospital.BLL.DTO.DeseaseRecordDTO>

@{
    ViewBag.Title = "История болезни";
}

<h2>История болезни</h2>

@foreach (var record in Model)
{
    <p class="history-header">@record.Date</p>
    <p class="history-body">@record.Text</p>
    <hr />
}

@if (!ViewBag.IsClosed && (ViewBag.Role == "admin" || ViewBag.Role == "doctor"))
{
    using (Html.BeginForm("AddRecord", "Desease", FormMethod.Post, new { @class = "form-inline", role = "form" }))
    {
        @Html.AntiForgeryToken();
        @Html.Hidden("DeseaseId", (int)ViewBag.Id)
        @Html.TextArea("Text", new { @class = "form-control" });
        <div class="form-group">
            <input type="submit" value="Добавить" class="btn btn-primary" />
        </div>
    }
}

@section menu{
    <div id="Update" class="menu-item">
        <p>Изменить</p>
    </div>
    <div id="History" class="menu-item active">
        <p>История</p>
    </div>
    <div id="ReverseToDesease" class="menu-item">
        <p>Вернуться</p>
    </div>
}

@section script{
    @Scripts.Render("~/bundles/myscripts")
    <script type="text/javascript">
        $('#Update').click(function () {
            location.href = '/Desease/UpdateDesease/' + @((int)ViewBag.Id);
        });
    </script>
}

MyHospital.Web/Views/Desease/Deseases.cshtml
@model IEnumerable<MyHospital.BLL.DTO.DeseaseDTO>

<h1>Болезни</h1>

@using (Html.BeginForm("Deseases", "Desease", FormMethod.Get, new { @class = "form-inline", role = "form" }))
{
    @Html.TextBox("Name", null, new { @class = "form-control", id = "DeseaseName" });
    <div class="form-group">
        <button id="SearchDesease" class="btn btn-primary">Искать</button>
    </div>
}

@if (Model.Count() == 0)
{
    <br/>
    <p>Нет болезней</p>
    <button id="AllDeseases" class="btn btn-info">Показать все</button>
}
else
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Название</th>
                <th>Лечаший врач</th>
                <th>Пациент</th>
                <th>Статус</th>
                <th>Дата начала</th>
                <th>Дата окончания</th>
                <th>Действия</th>
            </tr>
        </thead>
        @foreach (var desease in Model)
        {
            <tbody>
                <tr>
                    <td>@desease.Name</td>
                    <td>@desease.DoctorName</td>
                    <td>@desease.PatientName</td>
                    <td>@desease.Status</td>
                    <td>@desease.StartDate</td>
                    @if (desease.EndDate == null)
                    {
                        <td>Текущая</td>
                    }
                    else
                    {
                        <td>@desease.EndDate</td>
                    }
                    <td>
                        @Html.ActionLink("Параметры", "UpdateDesease", new { desease.Id })
                    </td>
                </tr>
            </tbody>
        }
    </table>
    <div class="btn-group">
        @for (int i = 0; i < ViewBag.PageCount; i++)
        {
            if (i == ViewBag.Page)
            {
                <a class="btn btn-primary" href="@Url.Action("Deseases", new { Page = i, Name = ViewBag.Name })">@(i + 1)</a>
            }
            else
            {
                <a class="btn selected btn-default" href="@Url.Action("Deseases", new { Page = i, Name = ViewBag.Name })">@(i + 1)</a>
            }
        }
    </div>
}



@section menu{
    <div id="Profile" class="menu-item">
        <p>Профиль</p>
    </div>
    <div id="Doctors" class="menu-item">
        <p>Доктора</p>
    </div>
    @if (ViewBag.Role == "doctor" || ViewBag.Role == "admin")
    {
        <div id="Patients" class="menu-item">
            <p>Пациенты</p>
         </div>
    }
    <div id="Deseases" class="menu-item active">
        <p>Болезни</p>
    </div>
    <div id="Logout" class="menu-item">
        <p>Выйти</p>
    </div>
}


@section script{
    @Scripts.Render("~/bundles/myscripts")
    <script type="text/javascript">
        $(function () {
            $('#SearchDesease').click(function () {
                var name = $("#DeseaseName").val();
                location.href = '/Desease/Deseases' + name;
            });
            $('#AllDeseases').click(function () {
                location.href = '/Desease/Deseases';
            });
        });
    </script>
}

MyHospital.Web/Views/Desease/SuccessCreateDesease.cshtml
<h2>Болезнь создана успешно</h2>

@Scripts.Render("~/bundles/jquery")
<script>
    $(document).ready(function () {
        setTimeout(function() {
            window.location.href = "@Url.Action("Doctors", "Account")";
        }, 1000);
    })
</script>

MyHospital.Web/Views/Desease/UpdateDesease.cshtml
@model MyHospital.Web.Models.UpdateDeseaseModel

<h2>Изменение болезни</h2>

<p>@Model.Message</p>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Параметр</th>
            <th>Текущее значение</th>
            @if ((ViewBag.Role == "doctor" || ViewBag.Role == "admin"))
            {
                <th>Новое значение</th>
            }
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <p>Название</p>
            </td>
            <td>
                <p>@Model.Name</p>
            </td>
            @if ((ViewBag.Role == "doctor" || ViewBag.Role == "admin"))
            {
                <td>
                    @using (Html.BeginForm("ChangeName", "Desease", FormMethod.Post, new { @class = "form-inline", role = "form" }))
                    {
                        @Html.AntiForgeryToken();
                        @Html.Hidden("DeseaseId", Model.Id);
                        <div class="form-group">
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = "Название" })
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Изменить" class="btn btn-primary" />
                        </div>
                    }
                </td>
            }
        </tr>
        <tr>
            <td>
                <p>Лечаший врач</p>
            </td>
            <td>
                <p>@Model.DoctorName</p>
            </td>
            @if ((ViewBag.Role == "doctor" || ViewBag.Role == "admin"))
            {
                <td>
                    @if (!ViewBag.IsClosed)
                    {
                        using (Html.BeginForm("ChangeDoctor", "Desease", FormMethod.Post, new { @class = "form-inline", role = "form" }))
                        {
                            @Html.AntiForgeryToken();
                            @Html.Hidden("DeseaseId", Model.Id);
                            <div class="form-group">
                                @Html.DropDownList("DoctorId", (SelectList)ViewBag.doctor)
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Изменить" class="btn btn-primary" />
                            </div>
                        }
                    }
                    else
                    {
                        <p>Болезнь закрыта</p>
                    }
                </td>
            }
        </tr>
        <tr>
            <td>
                <p>Статус</p>
            </td>
            <td>
                <p>@Model.Status</p>
            </td>
            @if ((ViewBag.Role == "doctor" || ViewBag.Role == "admin"))
            {
                <td>
                    @if (!ViewBag.IsClosed)
                {
                    using (Html.BeginForm("ChangeStatus", "Desease", FormMethod.Post, new { @class = "form-inline", role = "form" }))
                    {
                            @Html.AntiForgeryToken();
                            @Html.Hidden("DeseaseId", Model.Id);
                            <div class="form-group">
                                @Html.DropDownList("Status", (SelectList)ViewBag.statuses)
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Изменить" class="btn btn-primary" />
                            </div>
                        }
                    }
                    else
                    {
                        <p>Болезнь закрыта</p>
                    }
                </td>
            }
        </tr>
    </tbody>
</table>
<p class="history-header">Жалоба пациента</p>
<p class="history-body">@Model.Complaint</p>
<br /> 
@if ((ViewBag.Role == "doctor" || ViewBag.Role == "admin"))
{
    if (!ViewBag.IsClosed)
    {
        using (Html.BeginForm("CloseDesease", "Desease", FormMethod.Post, new { @class = "form-inline", role = "form" }))
        {
            @Html.AntiForgeryToken();
            @Html.Hidden("DeseaseId", Model.Id)
            <div class="form-group">
                <input type="submit" value="Закрыть болезнь" class="btn btn-primary" />
            </div>
        }
    }
    else
    {
        using (Html.BeginForm("ReOpenDesease", "Desease", FormMethod.Post, new { @class = "form-inline", role = "form" }))
        {
            @Html.AntiForgeryToken();
            @Html.Hidden("DeseaseId", Model.Id)
            <div class="form-group">
                <input type="submit" value="Восстановить болезнь" class="btn btn-primary" />
            </div>
        }
    }
    <br />
    using (Html.BeginForm("DeleteDesease", "Desease", FormMethod.Post, new { @class = "form-inline", role = "form", id = "delete" }))
    {
        @Html.AntiForgeryToken();
        @Html.Hidden("DeseaseId", Model.Id)
        <div class="form-group">
            <input type="submit" onClick="return confirm('Вы подтверждаете удаление?');" value="Удалить болезнь" class="btn btn-primary" />
        </div>
    }
}
@section menu{
    <div id="Update" class="menu-item active">
        <p>Изменить</p>
    </div>
    <div id="History" class="menu-item">
        <p>История</p>
    </div>
    <div id="ReverseToDesease" class="menu-item">
        <p>Вернуться</p>
    </div>
}

@section script{
    @Scripts.Render("~/bundles/myscripts")
    <script type="text/javascript">
        $('#History').click(function () {
            location.href = '/Desease/DeseaseHistory/' + @Model.Id;
        });
    </script>
}